Update bulkdig

diff --git a/bulkdig b/bulkdig
--- a/bulkdig
+++ b/bulkdig
@@ -1,4 +1,10 @@
 #!/bin/bash
+
+if [[ $1 != "a" ]] && [[ $1 != "mx" ]] && [[ $1 != "ns" ]] && [[ $1 != "txt" ]] && [[ $1 != "cname" ]] && [[ $1 != "" ]] && [[ $1 != "any" ]]; then
+  echo "Error, I accept only the following arguments: a, mx, txt, cname, any."
+        exit 1
+fi
+
 REDBG="\e[41m"
 NC="\033[0m"
 BOLD="\e[1m"
@@ -8,6 +14,13 @@ dt ()
     remove=$(echo $@ |  sed 's^https*^^' | sed 's^[,/*:]^^g' );
     dig any +trace +nocl +nodnssec $remove | sed "s/\($remove.*A\s*\([0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\)\)/dig -x \2 +short | xargs echo \"\1 ->\"/e"
 }
+
+dtcf ()
+{
+    remove=$(echo $@ |  sed 's^https*^^' | sed 's^[,/*:]^^g' );
+    dig +trace +nocl +nodnssec $remove | sed "s/\($remove.*A\s*\([0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\)\)/dig -x \2 +short | xargs echo \"\1 ->\"/e"
+}
+
 echo ""
 while read domain
 do
@@ -18,19 +31,33 @@ do
         ns=$(cat temp_resolver | sed -nE "/^$domain.+\b(NS)\b/p" | awk '{if (NF <= 4) print $(NF-1), $(NF); else if (NF = 6) print $(NF-3), $(NF-2), $(NF-1)}' | sort -u)
         txt=$(cat temp_resolver | sed -nE "/^$domain.+\b(TXT)\b/p" | cut -d \" -f 2 | sort -u)
         cname=$(cat temp_resolver | sed -nE "/^$domain.+\b(CNAME)\b/p" | awk '{if (NF <= 4) print $NF; else if (NF = 6) print $(NF-3), $(NF-2), $(NF-1)}' | sort -u)
-
+        if grep "ns\.cloudflare\.com" temp_resolver -q; then
+          if [[ $1 = mx ]] || [[ $1 = txt ]] || [[ $1 = any ]]; then
+            if [[ $1 = mx ]]; then
+              mx=$(dtcf $domain mx | sed -nE "/^$domain.+\b(MX)\b/p" | awk '{if (NF <= 4) print $NF; else if (NF = 6) print $(NF-3), $(NF-2), $(NF-1)}' | sort -u)
+            elif [[ $1 = txt ]]; then
+              txt=$(dtcf $domain txt | sed -nE "/^$domain.+\b(TXT)\b/p" | cut -d \" -f 2 | sort -u)
+            elif [[ $1 = any ]]; then
+              mx=$(dtcf $domain mx | sed -nE "/^$domain.+\b(MX)\b/p" | awk '{if (NF <= 4) print $NF; else if (NF = 6) print $(NF-3), $(NF-2), $(NF-1)}' | sort -u)
+              txt=$(dtcf $domain txt | sed -nE "/^$domain.+\b(TXT)\b/p" | cut -d \" -f 2 | sort -u)
+            fi
+          fi
+          dtcf $domain > temp_resolver_cf
+          a=$(cat temp_resolver_cf | sed -nE "/^$domain.+\b(A|CNAME)\b/p" | awk '{if (NF <= 4) print $NF; else if (NF = 6) print $(NF-3), $(NF-2), "->", $(NF)}' | sort -u)
+          cname=$(cat temp_resolver_cf | sed -nE "/^$domain.+\b(A|CNAME)\b/p" | awk '{if (NF <= 4) print $NF; else if (NF = 6) print $(NF-3), $(NF-2), "->", $(NF)}' | sort -u)
+        fi
 if [ ! $1 ] || [ $1 = "a" ]; then
 printf "${BOLD}${REDBG}$domain${NC} ${NC}\n"
         if [ ! -z "$a" ]; then
                 printf "$a\n"
-		fi
+                fi
         if [ ! -z "$cname" ]; then
-                printf "$cname\n"	
-		fi
+                printf "$cname\n"
+                fi
         if [ ! -z "$ns" ]; then
                 printf "$ns\n
 "
-		fi
+                fi
 
 
 elif [ $1 = "mx" ]; then
@@ -48,21 +75,21 @@ printf "${BOLD}${REDBG}$domain${NC} ${NC}\n"
         if [ ! -z "$a" ]; then
                 printf "$a\n
 "
-		fi
+                fi
         if [ ! -z "$cname" ]; then
                 printf "$cname\n
-"	
-		fi
+"
+                fi
 
 elif [ $1 = "any" ]; then
 printf "${BOLD}${REDBG}$domain${NC} ${NC}\n"
         if [ ! -z "$a" ]; then
                 printf "$a\n"
-		fi
+                fi
         if [ ! -z "$cname" ]; then
                 printf "$cname\n
-"	
-		fi
+"
+                fi
         if [ ! -z "$mx" ]; then
                 printf "$mx\n"
         fi
@@ -72,11 +99,9 @@ printf "${BOLD}${REDBG}$domain${NC} ${NC}\n"
         if [ ! -z "$ns" ]; then
                 printf "$ns\n
 "
-		fi
-else
-        echo "Error, I accept only the following arguments: a, mx, txt, cname, any."
-        break
+                fi
 fi
 done
 alias rm="rm"
 rm temp_resolver
+rm temp_resolver_cf
